/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  BodyLoginForTokenLoginPost,
  BodySaveDocumentDocumentInteractionIdUploadPost,
  DocumentOutput,
  DocumentUpdate,
  ExerciseItemOutput,
  ExerciseItemUpdate,
  InteractionInput,
  InteractionOutput,
  InteractionUpdate,
  LLMResponseInput,
  LLMResponseOutput,
  NoteInput,
  NoteOutput,
  NoteUpdate,
  ReadLlmResponsesLlmResponseInteractionIdGetParams,
  SaveDocumentDocumentInteractionIdUploadPostParams,
  StudyActivityInput,
  StudyActivityOutput,
  StudyActivityOutputComplete,
  StudyActivityUpdate,
  Token,
  UserInput,
  UserOutput,
  UserPasswordChange,
  UserUpdate
} from './api.schemas.ts';

export const getFastAPI = (axiosInstance: AxiosInstance = axios) => {
/**
 * Login endpoint. Returns a token when user enters correct credentials. Tokens have an expiration time.
 * @summary Login For Token
 */
const loginForTokenLoginPost = (
    bodyLoginForTokenLoginPost: BodyLoginForTokenLoginPost, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Token>> => {const formUrlEncoded = new URLSearchParams();
if(bodyLoginForTokenLoginPost.grant_type !== undefined && bodyLoginForTokenLoginPost.grant_type !== null) {
 formUrlEncoded.append(`grant_type`, bodyLoginForTokenLoginPost.grant_type);
 }
formUrlEncoded.append(`username`, bodyLoginForTokenLoginPost.username);
formUrlEncoded.append(`password`, bodyLoginForTokenLoginPost.password);
if(bodyLoginForTokenLoginPost.scope !== undefined) {
 formUrlEncoded.append(`scope`, bodyLoginForTokenLoginPost.scope);
 }
if(bodyLoginForTokenLoginPost.client_id !== undefined && bodyLoginForTokenLoginPost.client_id !== null) {
 formUrlEncoded.append(`client_id`, bodyLoginForTokenLoginPost.client_id);
 }
if(bodyLoginForTokenLoginPost.client_secret !== undefined && bodyLoginForTokenLoginPost.client_secret !== null) {
 formUrlEncoded.append(`client_secret`, bodyLoginForTokenLoginPost.client_secret);
 }

    return axiosInstance.post(
      `/login`,
      formUrlEncoded,options
    );
  }

/**
 * Embeds and saves a user-uploaded document to the database. Documents belong to an interaction.
 * @summary Save Document
 */
const saveDocumentDocumentInteractionIdUploadPost = (
    interactionId: number,
    bodySaveDocumentDocumentInteractionIdUploadPost: BodySaveDocumentDocumentInteractionIdUploadPost,
    params?: SaveDocumentDocumentInteractionIdUploadPostParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DocumentOutput>> => {const formData = new FormData();
formData.append(`file`, bodySaveDocumentDocumentInteractionIdUploadPost.file);

    return axiosInstance.post(
      `/document/${interactionId}/upload`,
      formData,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * Reads all documents in an interaction.
 * @summary Read All Documents
 */
const readAllDocumentsDocumentInteractionIdGet = (
    interactionId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DocumentOutput[]>> => {
    return axiosInstance.get(
      `/document/${interactionId}/`,options
    );
  }

/**
 * Updates a document's information. Document's contents cannot be updated.
 * @summary Update Document
 */
const updateDocumentDocumentDocumentIdPatch = (
    documentId: number,
    documentUpdate: DocumentUpdate, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DocumentOutput>> => {
    return axiosInstance.patch(
      `/document/${documentId}`,
      documentUpdate,options
    );
  }

/**
 * Deletes a document from an interaction.
 * @summary Delete Document
 */
const deleteDocumentDocumentDocumentIdDelete = (
    documentId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.delete(
      `/document/${documentId}`,options
    );
  }

/**
 * Creates an interaction.
 * @summary Create Interaction
 */
const createInteractionInteractionCreatePost = (
    interactionInput: InteractionInput, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<InteractionOutput>> => {
    return axiosInstance.post(
      `/interaction/create`,
      interactionInput,options
    );
  }

/**
 * Gets all interactions of the current user.
 * @summary Read All Interactions
 */
const readAllInteractionsInteractionGet = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<InteractionOutput[]>> => {
    return axiosInstance.get(
      `/interaction/`,options
    );
  }

/**
 * Updates an interaction's information.
 * @summary Update Interaction
 */
const updateInteractionInteractionInteractionIdPatch = (
    interactionId: number,
    interactionUpdate: InteractionUpdate, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<InteractionOutput>> => {
    return axiosInstance.patch(
      `/interaction/${interactionId}`,
      interactionUpdate,options
    );
  }

/**
 * Deletes an interaction, along with all of its associated information like uploaded documents, notes, history,...
 * @summary Delete Interaction
 */
const deleteInteractionInteractionInteractionIdDelete = (
    interactionId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.delete(
      `/interaction/${interactionId}`,options
    );
  }

/**
 * Receives a user prompt and returns the model's answer. Conversations (prompts and answers) belong to an interaction.
 * @summary Create Llm Response
 */
const createLlmResponseLlmResponseInteractionIdChatPost = (
    interactionId: number,
    lLMResponseInput: LLMResponseInput, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<LLMResponseOutput>> => {
    return axiosInstance.post(
      `/llm-response/${interactionId}/chat`,
      lLMResponseInput,options
    );
  }

/**
 * Reads past conversations in an interaction.
 * @summary Read Llm Responses
 */
const readLlmResponsesLlmResponseInteractionIdGet = (
    interactionId: number,
    params?: ReadLlmResponsesLlmResponseInteractionIdGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<LLMResponseOutput[]>> => {
    return axiosInstance.get(
      `/llm-response/${interactionId}/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * Creates a note. Notes belong to an interaction.
 * @summary Create Note
 */
const createNoteNoteInteractionIdUploadPost = (
    interactionId: number,
    noteInput: NoteInput, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<NoteOutput>> => {
    return axiosInstance.post(
      `/note/${interactionId}/upload`,
      noteInput,options
    );
  }

/**
 * Reads all notes related to an interaction.
 * @summary Read All Notes
 */
const readAllNotesNoteInteractionIdGet = (
    interactionId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<NoteOutput[]>> => {
    return axiosInstance.get(
      `/note/${interactionId}/`,options
    );
  }

/**
 * Updates a note.
 * @summary Update Note
 */
const updateNoteNoteNoteIdPatch = (
    noteId: number,
    noteUpdate: NoteUpdate, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<NoteOutput>> => {
    return axiosInstance.patch(
      `/note/${noteId}`,
      noteUpdate,options
    );
  }

/**
 * Deletes a note.
 * @summary Delete Note
 */
const deleteNoteNoteNoteIdDelete = (
    noteId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.delete(
      `/note/${noteId}`,options
    );
  }

/**
 * Creates a user account.
 * @summary Register User
 */
const registerUserUserRegisterPost = (
    userInput: UserInput, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserOutput>> => {
    return axiosInstance.post(
      `/user/register`,
      userInput,options
    );
  }

/**
 * Reads current user's public information.
 * @summary Read User
 */
const readUserUserMeGet = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserOutput>> => {
    return axiosInstance.get(
      `/user/me`,options
    );
  }

/**
 * Updates current user's public information.
 * @summary Update User
 */
const updateUserUserMePatch = (
    userUpdate: UserUpdate, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserOutput>> => {
    return axiosInstance.patch(
      `/user/me`,
      userUpdate,options
    );
  }

/**
 * Updates current user's password.
 * @summary Update Password
 */
const updatePasswordUserChangePasswordPatch = (
    userPasswordChange: UserPasswordChange, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.patch(
      `/user/change-password`,
      userPasswordChange,options
    );
  }

/**
 * Tạo một dạng tài liệu tùy vào các yêu cầu trong request.
 * @summary Create Study Activity
 */
const createStudyActivityStudyActivityInteractionIdCreatePost = (
    interactionId: number,
    studyActivityInput: StudyActivityInput, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<StudyActivityOutputComplete>> => {
    return axiosInstance.post(
      `/study-activity/${interactionId}/create`,
      studyActivityInput,options
    );
  }

/**
 * Đọc thông tin khái quát của tất cả dạng tài liệu đã tạo trong Interaction.
 * @summary Read All Study Activity
 */
const readAllStudyActivityStudyActivityInteractionIdGet = (
    interactionId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<StudyActivityOutput[]>> => {
    return axiosInstance.get(
      `/study-activity/${interactionId}/`,options
    );
  }

/**
 * Đọc thông tin chi tiết của một tài liệu.
 * @summary Read Study Activity Complete
 */
const readStudyActivityCompleteStudyActivityStudyActivityIdGet = (
    studyActivityId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<StudyActivityOutputComplete>> => {
    return axiosInstance.get(
      `/study-activity/${studyActivityId}`,options
    );
  }

/**
 * Xóa một tài liệu.
 * @summary Delete Study Activity
 */
const deleteStudyActivityStudyActivityStudyActivityIdDelete = (
    studyActivityId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.delete(
      `/study-activity/${studyActivityId}`,options
    );
  }

/**
 * Cập nhật thông tin khái quát của một tài liệu (tên và mô tả).
 * @summary Update Study Activity
 */
const updateStudyActivityStudyActivityStudyActivityIdUpdatePatch = (
    studyActivityId: number,
    studyActivityUpdate: StudyActivityUpdate, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<StudyActivityOutput>> => {
    return axiosInstance.patch(
      `/study-activity/${studyActivityId}/update`,
      studyActivityUpdate,options
    );
  }

/**
 * Trả lời MỘT câu hỏi trong một tài liệu dạng Exercise.
 * @summary Answer Exercise Item
 */
const answerExerciseItemStudyActivityExerciseItemIdAnswerPatch = (
    exerciseItemId: number,
    exerciseItemUpdate: ExerciseItemUpdate, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ExerciseItemOutput>> => {
    return axiosInstance.patch(
      `/study-activity/${exerciseItemId}/answer`,
      exerciseItemUpdate,options
    );
  }

/**
 * Nộp tài liệu dạng Exercise.
 * @summary Submit Exercise Activity
 */
const submitExerciseActivityStudyActivityStudyActivityIdSubmitPatch = (
    studyActivityId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<StudyActivityOutputComplete>> => {
    return axiosInstance.patch(
      `/study-activity/${studyActivityId}/submit`,undefined,options
    );
  }

return {loginForTokenLoginPost,saveDocumentDocumentInteractionIdUploadPost,readAllDocumentsDocumentInteractionIdGet,updateDocumentDocumentDocumentIdPatch,deleteDocumentDocumentDocumentIdDelete,createInteractionInteractionCreatePost,readAllInteractionsInteractionGet,updateInteractionInteractionInteractionIdPatch,deleteInteractionInteractionInteractionIdDelete,createLlmResponseLlmResponseInteractionIdChatPost,readLlmResponsesLlmResponseInteractionIdGet,createNoteNoteInteractionIdUploadPost,readAllNotesNoteInteractionIdGet,updateNoteNoteNoteIdPatch,deleteNoteNoteNoteIdDelete,registerUserUserRegisterPost,readUserUserMeGet,updateUserUserMePatch,updatePasswordUserChangePasswordPatch,createStudyActivityStudyActivityInteractionIdCreatePost,readAllStudyActivityStudyActivityInteractionIdGet,readStudyActivityCompleteStudyActivityStudyActivityIdGet,deleteStudyActivityStudyActivityStudyActivityIdDelete,updateStudyActivityStudyActivityStudyActivityIdUpdatePatch,answerExerciseItemStudyActivityExerciseItemIdAnswerPatch,submitExerciseActivityStudyActivityStudyActivityIdSubmitPatch}};
export type LoginForTokenLoginPostResult = AxiosResponse<Token>
export type SaveDocumentDocumentInteractionIdUploadPostResult = AxiosResponse<DocumentOutput>
export type ReadAllDocumentsDocumentInteractionIdGetResult = AxiosResponse<DocumentOutput[]>
export type UpdateDocumentDocumentDocumentIdPatchResult = AxiosResponse<DocumentOutput>
export type DeleteDocumentDocumentDocumentIdDeleteResult = AxiosResponse<void>
export type CreateInteractionInteractionCreatePostResult = AxiosResponse<InteractionOutput>
export type ReadAllInteractionsInteractionGetResult = AxiosResponse<InteractionOutput[]>
export type UpdateInteractionInteractionInteractionIdPatchResult = AxiosResponse<InteractionOutput>
export type DeleteInteractionInteractionInteractionIdDeleteResult = AxiosResponse<void>
export type CreateLlmResponseLlmResponseInteractionIdChatPostResult = AxiosResponse<LLMResponseOutput>
export type ReadLlmResponsesLlmResponseInteractionIdGetResult = AxiosResponse<LLMResponseOutput[]>
export type CreateNoteNoteInteractionIdUploadPostResult = AxiosResponse<NoteOutput>
export type ReadAllNotesNoteInteractionIdGetResult = AxiosResponse<NoteOutput[]>
export type UpdateNoteNoteNoteIdPatchResult = AxiosResponse<NoteOutput>
export type DeleteNoteNoteNoteIdDeleteResult = AxiosResponse<void>
export type RegisterUserUserRegisterPostResult = AxiosResponse<UserOutput>
export type ReadUserUserMeGetResult = AxiosResponse<UserOutput>
export type UpdateUserUserMePatchResult = AxiosResponse<UserOutput>
export type UpdatePasswordUserChangePasswordPatchResult = AxiosResponse<void>
export type CreateStudyActivityStudyActivityInteractionIdCreatePostResult = AxiosResponse<StudyActivityOutputComplete>
export type ReadAllStudyActivityStudyActivityInteractionIdGetResult = AxiosResponse<StudyActivityOutput[]>
export type ReadStudyActivityCompleteStudyActivityStudyActivityIdGetResult = AxiosResponse<StudyActivityOutputComplete>
export type DeleteStudyActivityStudyActivityStudyActivityIdDeleteResult = AxiosResponse<void>
export type UpdateStudyActivityStudyActivityStudyActivityIdUpdatePatchResult = AxiosResponse<StudyActivityOutput>
export type AnswerExerciseItemStudyActivityExerciseItemIdAnswerPatchResult = AxiosResponse<ExerciseItemOutput>
export type SubmitExerciseActivityStudyActivityStudyActivityIdSubmitPatchResult = AxiosResponse<StudyActivityOutputComplete>
