/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type DocumentType = typeof DocumentType[keyof typeof DocumentType];


export const DocumentType = {
  PDF: 'PDF',
  IMAGE: 'IMAGE',
  TEXT: 'TEXT',
} as const;
