/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { DocumentType } from './documentType';

export interface DocumentOutput {
  name: string;
  page_starts_at?: number;
  id: number;
  created_at: string;
  type: DocumentType;
}
