/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface DocumentUpdate {
  name?: string | null;
  page_starts_at?: number | null;
}
