/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type ExceptionType = typeof ExceptionType[keyof typeof ExceptionType];


export const ExceptionType = {
  REQUEST: 'REQUEST',
  AUTHENTICATION: 'AUTHENTICATION',
  NOT_FOUND: 'NOT_FOUND',
  METHOD: 'METHOD',
  TAKEN_INFO: 'TAKEN_INFO',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;
