/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ExceptionType } from './exceptionType';

export interface ExceptionResponse {
  exception_type: ExceptionType;
  message: string;
}
