/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type ExerciseItemContentType = typeof ExerciseItemContentType[keyof typeof ExerciseItemContentType];


export const ExerciseItemContentType = {
  MULTIPLE_CHOICE_QUESTIONS_CHOICE: 'MULTIPLE_CHOICE_QUESTIONS_CHOICE',
} as const;
