/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ExerciseItemContentOutput } from './exerciseItemContentOutput';

export interface ExerciseItemOutput {
  max_score: number;
  question: string;
  id: number;
  user_score: number;
  attempt: string | null;
  contents: ExerciseItemContentOutput[];
}
