/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ExerciseItemContentType } from './exerciseItemContentType';

export interface ExerciseItemContentOutput {
  content: string;
  type: ExerciseItemContentType;
  id: number;
  is_correct?: boolean | null;
}
