/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface LLMResponseOutput {
  prompt: string;
  id: number;
  answer: string;
  created_at: string;
}
