/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface NoteOutput {
  name: string;
  description?: string;
  content?: string;
  id: number;
  created_at: string;
}
