/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type ReviewItemContentType = typeof ReviewItemContentType[keyof typeof ReviewItemContentType];


export const ReviewItemContentType = {
  FLASHCARDS_FRONT: 'FLASHCARDS_FRONT',
  FLASHCARDS_BACK: 'FLASHCARDS_BACK',
  GAP_FILL_TEXT: 'GAP_FILL_TEXT',
  GAP_FILL_CORRECT: 'GAP_FILL_CORRECT',
  GAP_FILL_DISTRACTOR: 'GAP_FILL_DISTRACTOR',
} as const;
