/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ReviewItemContentOutput } from './reviewItemContentOutput';

export interface ReviewItemOutput {
  id: number;
  contents: ReviewItemContentOutput[];
}
