/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type StudyActivityType = typeof StudyActivityType[keyof typeof StudyActivityType];


export const StudyActivityType = {
  REVIEW: 'REVIEW',
  EXERCISE: 'EXERCISE',
} as const;
