/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type StudyActivityFormat = typeof StudyActivityFormat[keyof typeof StudyActivityFormat];


export const StudyActivityFormat = {
  MULTIPLE_CHOICE_QUESTIONS: 'MULTIPLE_CHOICE_QUESTIONS',
  OPEN_ENDED: 'OPEN_ENDED',
  FLASHCARDS: 'FLASHCARDS',
  GAP_FILL: 'GAP_FILL',
} as const;
