/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { StudyActivityFormat } from './studyActivityFormat';
import type { StudyActivityType } from './studyActivityType';
import type { SubjectType } from './subjectType';

export interface StudyActivityOutput {
  prompt: string;
  activity_type: StudyActivityType;
  activity_format: StudyActivityFormat;
  subject_type: SubjectType;
  id: number;
  name: string;
  description: string;
  created_at: string;
  is_submitted: boolean;
  submitted_at: string | null;
  total_score: number | null;
}
