/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type SubjectType = typeof SubjectType[keyof typeof SubjectType];


export const SubjectType = {
  MATHS: 'MATHS',
  ENGLISH: 'ENGLISH',
  VIETNAMESE: 'VIETNAMESE',
} as const;
