/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface UserUpdate {
  /** @minLength 1 */
  username?: string | null;
  email?: string | null;
}
